import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'public');const host=process.argv.includes('--lan')?'0.0.0.0':'127.0.0.1';const port=3103;
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.png':'image/png'};
const server=http.createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const offline=pathname==='/offline.html';const file=offline?path.join(path.dirname(root),'Olm-3D-Offline.html'):path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!offline&&file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}const bytes=await fs.readFile(file);res.setHeader('Content-Type',file.endsWith('.json.gz')?'application/json':types[path.extname(file)]||'application/octet-stream');if(file.endsWith('.gz'))res.setHeader('Content-Encoding','gzip');res.setHeader('Cache-Control','no-cache');res.writeHead(200);res.end(bytes);}catch{res.writeHead(404);res.end('Not found');}});
server.on('error',error=>{console.error(error.code==='EADDRINUSE'?'Port 3103 is already in use. Open http://localhost:3103 or close the earlier trainer window.':error.message);process.exitCode=1;});
server.listen(port,host,()=>{console.log(`Olm 3D trainer: http://localhost:${port}`);if(host==='0.0.0.0')for(const addresses of Object.values(os.networkInterfaces()))for(const address of addresses||[])if(address.family==='IPv4'&&!address.internal)console.log(`Phone on the same Wi-Fi: http://${address.address}:${port}`);console.log('Keep this window open. Press Ctrl+C to stop.');});
